### ISSUE TITLE
Only directory, not complete path to file given to input of rule predict_genes_genomes

### ISSUE THREAD

**Issue by mdehollander** [metagenome-atlas/atlas#218] opened 2019-07-03 14:37 UTC
```
rule predict_genes_genomes:
    input: genomes/genomes/MAG4.fasta, genomes/genomes/MAG5.fasta, genomes/genomes/MAG6.fasta, genomes/genomes/MAG7.fasta, genomes/genomes/MAG1.fasta, genomes/genomes/MAG2.fasta, genomes/genomes/MAG3.fasta
    output: genomes/annotations/genes
    log: logs/genomes/prodigal.log
    jobid: 160


subprocess.CalledProcessError: Command 'set -euo pipefail;  prodigal -i genomes/genomes -o genomes/annotations/genes/genomes.gff -d genomes/annotations/genes/genomes.fna -a genomes/annotations/genes/genomes.faa -p meta -f gff 2>> logs/genomes/prodigal.log' returned non-zero exit status 18
```

Maybe related to #217 because the function `get_genomes_fasta` from `genomes.smk` is used as input for the rule `predict_genes_genomes` and also used the `os.path.join` function?

**Comment by SilasK** [comment] 2019-07-05 08:51
Duplicate of #216

**Closed** 2019-07-05 08:51 UTC
