### ISSUE TITLE
gtdb certificate has expired

### ISSUE THREAD

**Issue by Mechah** [metagenome-atlas/atlas#478] opened 2021-11-25 08:09 UTC
Hi Silas,
I made some test runs with ATLAS v. 2.8.1 and I'm pretty impressed how most of the steps are working and how efficient ATLAS is already! Maybe also the workshop helped a little on my end ;-)
What I'm struggeling with is an error when ATLAS tries to download the GTDB database. It seems the certificate has expired. I receive the following error (see below). Unfortunately, downloading the files first and placing them in the respective databases folder did not resovle the issue. ATLAS just removed those files again. Is there an option to omit downloading the databases each time when you want to run ATLAS?
Thanks for your help!

Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Singularity containers: ignored

[Wed Nov 24 19:01:05 2021]
rule download_gtdb:
    output: /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06, /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06/downloaded_success
    jobid: 0
    resources: mem_mb=220000, disk_mb=1000, tmpdir=/media/temp/2004, time=24, mem=220, time_min=1440

Activating conda environment: /home/cluster/o_mahnerta/NIBSC_CS690/databases/conda_envs/78d7197b37ff5cd20aa33a1a46596207
mkdir: cannot create directory ‘/home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06’: File exists
Downloading the GTDB-Tk database to /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06...
--2021-11-24 19:01:11--  https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz
Resolving data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)... 203.101.230.53
Connecting to data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)|203.101.230.53|:443... connected.
ERROR: The certificate of ‘data.gtdb.ecogenomic.org’ is not trusted.
ERROR: The certificate of ‘data.gtdb.ecogenomic.org’ has expired.
The certificate has expired
[Wed Nov 24 19:01:12 2021]
Error in rule download_gtdb:
    jobid: 0
    output: /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06, /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06/downloaded_success
    conda-env: /home/cluster/o_mahnerta/NIBSC_CS690/databases/conda_envs/78d7197b37ff5cd20aa33a1a46596207
    shell:
        GTDBTK_DATA_PATH=/home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06 ;  mkdir $GTDBTK_DATA_PATH ;download-db.sh ;
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job download_gtdb since they might be corrupted:
/home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by Mechah** [comment] 2021-11-25 08:53
P.S. One idea would be to change the downloading path to this one:
https://data.ace.uq.edu.au/public/gtdb/data/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz
Here there are no complains about the expired certificate.
Could you tell me where I could/should change this path?
Thanks.

**Comment by SilasK** [comment] 2021-11-26 15:50
Thank you for the feedback. I use the gtdb script to download the data. I don't know if I can change the path. But I check.  If you manage to download and unpack the data in the right folder you just need to run 
```
 touch /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06/downloaded_success
```

And atlas should accept it. Bit check with a dryrun first.

**Comment by Mechah** [comment] 2021-11-30 16:26
Great idea, but unfortunately, this hack did not work...
I have the unpacked data in the path .../databases/GTDB_V06/release202/ and created the file in .../databases/GTDB_V06/downloaded_success
However, I get this error report (genomes/taxonomy/gtdb/gtdbtk.log is empty):

Building DAG of jobs...
Updating job identify.
Using shell: /bin/bash
Provided cores: 48
Rules claiming more threads will be scaled down.
Singularity containers: ignored

[Tue Nov 30 16:06:10 2021]
rule identify:
    input: genomes/genomes, /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06, /home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06/downloaded_success
    output: genomes/taxonomy/gtdb/identify
    log: logs/taxonomy/gtdbtk/identify.txt, genomes/taxonomy/gtdb/gtdbtk.log
    jobid: 0
    threads: 48
    resources: mem_mb=220000, disk_mb=1000, tmpdir=/media/temp/2004, mem=220, time=5, time_min=300

Activating conda environment: /home/cluster/o_mahnerta/NIBSC_CS690/databases/conda_envs/78d7197b37ff5cd20aa33a1a46596207
[Tue Nov 30 16:06:27 2021]
Error in rule identify:
    jobid: 0
    output: genomes/taxonomy/gtdb/identify
    log: logs/taxonomy/gtdbtk/identify.txt, genomes/taxonomy/gtdb/gtdbtk.log (check log file(s) for error message)
    conda-env: /home/cluster/o_mahnerta/NIBSC_CS690/databases/conda_envs/78d7197b37ff5cd20aa33a1a46596207
    shell:
        GTDBTK_DATA_PATH=/home/cluster/o_mahnerta/NIBSC_CS690/databases/GTDB_V06 ; gtdbtk identify --genome_dir genomes/genomes --out_dir genomes/taxonomy/gtdb --extension fasta --cpus 48 &> logs/taxonomy/gtdbtk/identify.txt
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

**Comment by Mechah** [comment] 2021-12-02 08:42
Hi Silas, meanwhile the certificate of the GTDB repo was restored and my first atlas run all command completed with 100%.
Awesome!
I think you can close this issue...

**Comment by LLansing** [comment] 2022-01-07 21:13
I am reporting a very similar issue during the download_gtdb rule:

> --2022-01-05 19:16:38--  https://data.gtdb.ecogenomic.org/releases/release202/202.0/auxillary_files/gtdbtk_r202_data.tar.gz
Resolving data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)... 203.101.230.53
Connecting to data.gtdb.ecogenomic.org (data.gtdb.ecogenomic.org)|203.101.230.53|:443... connected.
ERROR: cannot verify data.gtdb.ecogenomic.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to data.gtdb.ecogenomic.org insecurely, use `--no-check-certificate'.

There are some things I think I could try to find a solution on my own, but I installed Atlas via conda and I cannot find the actual Atlas code (e.g. Snakefile, rule files, etc). Do you know how I can located the Atlas code relative to the Atlas conda installation?

**Comment by SilasK** [comment] 2022-01-12 13:30
First check you have up to data atlas version >=2.8

Apparently, it seems to be a temporary issue. no. Try again.

You know how to modify the snakemake? Otherwise I can download the gtdb data externally but you need to touch the output file of the download_gtdb rule 
You can find atlas by `python -c "import atlas; print(atlas.__file__)"`

**Comment by LLansing** [comment] 2022-01-27 00:19
My version was up to date and repeated attempts over 2 weeks provided the same error.
I attempted a solution by setting gtdbtk to its newest version in the conda env `gtdbtk.yaml` (1.7), but the same error occurred.

I was able to bypass this step by providing my own GTDB installation and touching the file `downloaded_success`

**Comment by SilasK** [comment] 2022-02-02 07:32
Good it worked for you. Did anyone else have this gtdb problem?

**Comment by LLansing** [comment] 2022-02-02 17:08
At least in my case, the expired GTDB certificate problem is likely being caused by our server side, relating to an intermediary Let's Encrypt certificate chain. Workarounds are discussed in [this blog post](https://www.openssl.org/blog/blog/2021/09/13/LetsEncryptRootCertExpire/). 
Therefore the problem is not due to Atlas.

**Closed** 2022-02-03 06:28 UTC
