### ISSUE TITLE
Error running "concoct"

### ISSUE THREAD

**Issue by telatin** [metagenome-atlas/atlas#245] opened 2019-10-02 14:22 UTC
Using atlas version 2.1.6 under conda 4.7.12, 
```
Error in rule run_concoct:
    jobid: 183
    output: B01/binning/concoct/intermediate_files/clustering_gt1000.csv
    log: B01/binning/concoct/intermediate_files/log.txt (check log file(s) for error message)
    conda-env: /qi/db/atlas/conda_envs/e65169e6
    shell:
        
        concoct -c 200             --coverage_file B01/binning/coverage/combined_coverage.tsv             --composition_file B01/B01_contigs.fasta             --basename B01/binning/concoct/intermediate_files             --read_length 100             --length_threshold 1000             --converge_out             --iterations 500
       
```

Running the offending command alone I get:
```
/home/ubuntu/miniconda3/lib/python3.6/site-packages/concoct/input.py:90: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing
[...]
AttributeError: 'numpy.dtype' object has no attribute 'value_counts'
```

**Comment by SilasK** [comment] 2019-10-02 15:40
Can you send me the conntent of B01/binning/concoct/intermediate_files/log.txt

I don't think that eunning the offending command with python3.6 gives the same error as in the pipeline.

**Comment by SilasK** [comment] 2019-10-13 11:10
Duplicate of #248

**Closed by SilasK** 2019-10-13 11:10 UTC
