### ISSUE TITLE
Maxbin error

### ISSUE THREAD

**Issue by gruningerrj** [metagenome-atlas/atlas#329] opened 2020-10-28 18:35 UTC
I am trying to setup the ATLAS pipeline and run the test data but am getting an cryptic error at the maxbin step. It doesn't really say what is going on and the maxbin log file it says the error is located is empty so I have no idea how to get past this step.

**Comment by gruningerrj** [comment] 2020-10-28 19:29
This is the error message
<img width="954" alt="Maxbin_error" src="https://user-images.githubusercontent.com/73610531/97486792-8cb1a680-1921-11eb-8a9e-f2cd181ad1ac.png">

**Comment by SilasK** [comment] 2020-10-28 20:19
duplicate of #328 I asume

**Closed by SilasK** 2020-10-28 20:19 UTC

**Comment by gruningerrj** [comment] 2020-10-28 20:21
No this was not a duplicate.

**Comment by SilasK** [comment] 2020-10-28 20:32
Check the "sample1/logs/binning/maxbin.log”

I assume you get a similar error as in #328
We are working on this.

As a temporary fix you could set ‘final_binner: metabat’ in the config file.

**Comment by gruningerrj** [comment] 2020-10-28 20:35
I did check the logs but they do not have anything in them.

I will try forcing it to use metabat

**Comment by SilasK** [comment] 2020-10-28 20:38
That’s true the error message is not printed in the log file but to the stdout which you can’t see due to the screen . Sorry, for that.

**Comment by gruningerrj** [comment] 2020-10-28 21:58
Thank you Silas. Setting the final binner to metabat forced it to move past that error with maxbin.
