### ISSUE TITLE
error returned non-zero exit status 1

### ISSUE THREAD

**Issue by ayixon** [metagenome-atlas/atlas#215] opened 2019-06-19 04:16 UTC
Hello Silas, your former comments were fine. 
"Atlas run qc" was well. Then, i run "atlas run assembly" but a i got this error:

Error in rule run_spades:
    jobid: 63
    output: SRR2107184-1/assembly/contigs.fasta, SRR2107184-1/assembly/scaffolds.fasta
    log: SRR2107184-1/logs/assembly/spades.log (check log file(s) for error message)
    conda-env: /tmpu/ayixon_g/ayixon/AssemTextil/Atlas/databases/conda_envs/3d81cc63
    shell:
        spades.py  --threads 8  --memory 250  -o SRR2107184-1/assembly  -k auto --meta     -s SRR2107184-1/assembly/reads/QC.errorcorr_se.fastq.gz     --only-assembler  > SRR2107184-1/logs/assembly/spades.log 2>&1 
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /tmpu/ayixon_g/ayixon/AssemTextil/Atlas/.snakemake/log/2019-06-18T204321.577543.snakemake.log
[2019-06-18 20:45 CRITICAL] Command 'snakemake --snakefile /tmpu/ayixon_g/ayixon/sw/atlas/atlas/Snakefile --directory /tmpu/ayixon_g/ayixon/AssemTextil/Atlas --jobs 16 --rerun-incomplete --configfile '/tmpu/ayixon_g/ayixon/AssemTextil/Atlas/config.yaml' --nolock  --use-conda  --conda-prefix /tmpu/ayixon_g/ayixon/AssemTextil/Atlas/databases/conda_envs   assembly   ' returned non-zero exit status 1.

Any suggestions? Thanks

**Comment by SilasK** [comment] 2019-06-19 07:29
I would do what the log says.
log: SRR2107184-1/logs/assembly/spades.log (check log file(s) for error message)

This was not run on a cluster was it?

**Comment by ayixon** [comment] 2019-06-19 13:29
Yes, it was run on a cluster. Thats the output for the spades.log file:

== Error ==  you cannot specify any data types except a single paired-end library (optionally accompanied by a single library of TSLR-contigs, or PacBio reads, or Nanopore reads) in metaSPAdes mode!

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

**Comment by SilasK** [comment] 2019-06-19 17:26
Here you have the problem. Metaspades cannot assemble a single end library.

You don’t have interleaved files, do you? If yes, have you marked it in the config file?
If you want to assemble single end library, either use megahit or spades. Set the ‘spades_preset’ to “normal”.

**Comment by ayixon** [comment] 2019-06-21 14:00
You rock..."Set the ‘spades_preset’ to “normal” works fine. Thanks very much

**Comment by ereyred** [comment] 2020-11-18 04:43
Hello, I get the same error - how does one go about setting the ‘spades_preset’ to “normal”? If possible, could you explain like I'm five? Thanks so much!

**Comment by ereyred** [comment] 2020-11-18 05:25
Hello I changed spades_preset to "normal" and it still gives me this error:

Error in rule run_spades:
    jobid: 764
    output: Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/assembly/contigs.fasta, Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/assembly/scaffolds.fasta
    log: Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/logs/assembly/spades.log (check log file(s) for error message)
    conda-env: /home/elvira/test/metaG/databases/conda_envs/ca7ea380
    shell:
        spades.py  --threads 1  --memory 250  -o Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/assembly  -k auto --meta     -s Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/assembly/reads/QC.errorcorr_se.fastq.gz     --only-assembler  > Meta-G1-FDSW202485731-1r-HCJTKDSXY-L4-2/logs/assembly/spades.log 2>&1
        (exited with non-zero exit code)

Could you help? :S Thanks so much!

**Comment by ereyred** [comment] 2020-11-18 05:43
I also updated snakemake to 5.9 and now it says "(one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)"

**Comment by ereyred** [comment] 2020-11-18 05:59
Hello I changed spades_preset to "normal" and it still gives me this error:
== Error ==  you cannot specify any data types except a single paired-end library (optionally accompanied by a single library of TSLR-contigs, or PacBio reads, or Nanopore reads) in metaSPAdes mode!
Could you help? :S Thanks so much!

**Comment by SilasK** [comment] 2020-11-23 11:03
It might be that there is some error in my code. But could you remove the log file in question and also all the {sample}/assembly/params.txt files. If they exist, spades try to continue from the previous run.

**Comment by ZoeHansen** [comment] 2020-12-24 21:03
Hi! First, thank you for developing ATLAS and monitoring GitHub so closely -- your other comments/suggestions for other issues have helped me out a lot! 

Unfortunately, I have a similar issue as ayixon in that I am receiving this error message during the 'assembly' stage. I am trying to perform 'atlas run all' with the test_reads that were provided in your [Docs](https://metagenome-atlas.readthedocs.io/en/latest/usage/getting_started.html) only I am using MEGAHIT for assembly rather than Spades:

`Error in rule run_megahit:
    jobid: 125
    output: sample2/assembly/megahit/sample2_prefilter.contigs.fa
    log: sample2/logs/assembly/megahit.log (check log file(s) for error message)
    conda-env: /mnt/ufs18/home-035/hansenzo/Database/conda_envs/ef4595df
    shell:

                rm -r sample2/assembly/megahit 2> sample2/logs/assembly/megahit.log

megahit -1 sample2/assembly/reads/QC.errorcorr.merged_R1.fastq.gz -2 sample2/assembly/reads/QC.errorcorr.merged_R2.fastq.gz --read sample2/assembly/reads/QC.errorcorr.merged_co.fastq.gz                 --tmp-dir /tmp/local/10301347 --num-cpu-threads 1 --k-min 21 --k-max 121 --k-step 20--out-dir sample2/assembly/megahit                 --out-prefix sample2_prefilter --min-contig-len 300  --min-count 2 --merge-level 20,0.98 --prune-level 2 --low-local-ratio 0.2                 --memory 250000000000 >> sample2/logs/assembly/megahit.log 2>&1

        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: ~/ATLAS_test/.snakemake/log/2020-12-24T130920.438838.snakemake.log
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
`

When I go to the 'megahit.log' file for Sample 2, this is what it says:

`Traceback (most recent call last):
  File "/mnt/ufs18/home-035/hansenzo/Database/conda_envs/ef4595df/bin/megahit", line 1143, in <module>
    sys.exit(main())
  File "/mnt/ufs18/home-035/hansenzo/Database/conda_envs/ef4595df/bin/megahit", line 1071, in main
    make_out_dir()
  File "/mnt/ufs18/home-035/hansenzo/Database/conda_envs/ef4595df/bin/megahit", line 183, in make_out_dir
    opt.temp_dir = tempfile.mkdtemp(dir = opt.temp_dir, prefix = 'megahit_tmp_') + "/"
  File "/mnt/ufs18/home-035/hansenzo/Database/conda_envs/ef4595df/lib/python3.6/tempfile.py", line 370, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/local/10301347/megahit_tmp_dcgsksog'
`

I'm not familiar enough with MEGAHIT to determine whether this is an issue with the code/parameters included in the config.yaml file or if this goes deeper  -- it looks like a temporary directory/file is not being created correctly, but I'm not sure if this is the actual problem or, if it is, how I should go about fixing it. Any help and advice is greatly appreciated! Thank you!

**Comment by SilasK** [comment] 2021-01-04 11:57
Yes, as I understand the error message it's that megahit can't create the temp dir. 

Check. does the `/tmp/` file exist on your computer/cluster? 
Do you have write access to it? Can you run `mkdir -p /tmp/local/10301347`

You can change the tmp directory in the config file. for the test run you might want to put it in a sub directory of you home directors. I don't recommend this for a real atlas run.

**Comment by ZoeHansen** [comment] 2021-01-25 17:57
Hi @SilasK -- I'm sorry for being so late in responding to your post. Thank you very much for your response! 

I had been running into a few seemingly random issues when trying to run my own install of ATLAS, and so had reached out to the research consultants at our High Performance Computing center to see if they would complete a system-wide install accessible to all users. They have been really helpful in troubleshooting, but have also appeared to hit a wall when running ATLAS

One of our consultants has given me the error report that seems to be resurfacing with our HPC use of ATLAS. Briefly, it appears that an error occurs when initializing CheckM and that this could be related to where the command is being run. If you're able, our consultant has compiled her errors and questions in the attached document. I thought I would place this question here, but please let me know if I should open a new/separate issue. Any help or advice would be greatly appreciated! Thank you, again! 

[error-report.txt](https://github.com/metagenome-atlas/atlas/files/5868556/error-report.txt)

**Comment by SilasK** [comment] 2021-01-25 19:22
Atlas was designed to install all dependencies in the database_dir/conda envs which seems to have worked. If you want you can also make this location shared between all users, if there are other users accessing the databases.


It seems to me that you have checkm installed twice.
One with atlas and one in /opt/software/CheckM/1.1.3-intel-2020a-Python-3.8.2/lib/python3.8/site-packages/checkm

The later takes priority over the one installed with conda.

Is it possible to remove the system installed checkM from your path or python path e.g. don’t load the module. Otherwise is it possible to change the priorities.

**Closed** 2021-09-07 19:55 UTC
