### ISSUE TITLE
Error in rule run_all_checkm_lineage_wf:

### ISSUE THREAD

**Issue by tianlei22** [metagenome-atlas/atlas#232] opened 2019-09-20 06:37 UTC
I also have error in rule run_all_checkm_lineage_wf:
![1568961290(1)](https://user-images.githubusercontent.com/55546015/65304738-f7879e80-dbb3-11e9-9480-fa27315993f0.png)
  
How can I deal with it.

**Comment by SilasK** [comment] 2019-09-20 12:37
Duplicate of #231

**Closed by SilasK** 2019-09-20 12:37 UTC
