### ISSUE TITLE
Error with snakemake checkpoints.

### ISSUE THREAD

**Issue by mdehollander** [metagenome-atlas/atlas#217] opened 2019-07-03 14:25 UTC
Using the latest version of atlas we get this error:

```
Error in rule get_genome_for_cat:
    jobid: 0
    output: genomes/taxonomy/MAG1/MAG1.fasta

RuleException:

IsADirectoryError in line 14 of ***/atlas/atlas/rules/cat_taxonomy.smk:

[Errno 21] Is a directory: 'genomes/genomes'
```

I think this is a regression introduced at PR #214: https://github.com/metagenome-atlas/atlas/pull/214/commits/6888f583195264e268e7d9cecb4bb6dc5da0ae37

In our situtation the snakemake input variable does not join the genomes directory (`genomes/genomes`) with the fasta file (`MAG1.fasta`)

**Comment by SilasK** [comment] 2019-07-05 08:51
Duplicate of #216

**Comment by SilasK** [comment] 2019-07-11 19:14
I repeat my answer here:

@mdehollander can you try to remove (or better rename ) the '.snakemake' subdir in your working dir and the genomes/genomes folder.

Try to rerun atlas with dry-run.

If atlas wants to redo many already performed steps, e.g. assembly you can first do atlas run genomes --touch this updates the timestamp of all the files. then you should run atlas run genomes and we'll see if now the checkpoint passes.

**Comment by mdehollander** [comment] 2019-07-15 12:19
ok, we can continue the discussion here because they seem not to be directly linked.

We renamed the `.snakemake` folder and since only a few rules are scheduled to be executed we started atlas directly. It gives the same error as before:
```
Job counts:
        count   jobs
        2       align_reads_to_MAGs
        2       bam_2_sam_MAGs
        1       cat_get_name
        7       cat_on_bin
        1       combine_bined_coverages_MAGs
        1       combine_coverages_MAGs
        2       convert_sam_to_bam
        1       fasttree
        1       genomes
        7       get_genome_for_cat
        1       merge_taxonomy
        1       parse_cat_output
        2       pileup_MAGs
        1       root_tree
        1       run_all_checkm_lineage_wf
        1       run_checkm_tree_qa
        32
This was a dry-run (flag -n). The order of jobs does not reflect the order of execution.

[Mon Jul 15 14:11:05 2019]
Error in rule get_genome_for_cat:
    jobid: 0
    output: genomes/taxonomy/MAG3/MAG3.fasta

RuleException:
IsADirectoryError in line 14 of ***/atlas_snakemake5.5.2/atlas/atlas/rules/cat_taxonomy.smk:
[Errno 21] Is a directory: 'genomes/genomes'
  File "***/atlas_snakemake5.5.2/atlas/atlas/rules/cat_taxonomy.smk", line 14, in __rule_get_genome_for_cat
  File "***.conda/envs/atlas_sm5.5.2/lib/python3.6/shutil.py", line 241, in copy
  File "***.conda/envs/atlas_sm5.5.2/lib/python3.6/shutil.py", line 120, in copyfile
  File "***.conda/envs/atlas_sm5.5.2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
```

**Comment by SilasK** [comment] 2019-07-15 12:26
Could you also delete the `genomes/genomes` folder and the .snakemake subfolder? This should restart the `rename_genomes` checkpoint, which at the center of the issue. 
Maybe also upgrading to snakemake v.5.5.3 could be an option.

**Comment by mdehollander** [comment] 2019-07-16 08:41
We did that, but without success. Also starting from scratch using snakemake 5.5.3 gives the same error.

I have the feeling that the bug is in the input function of the `get_genome_for_cat` rule: https://github.com/metagenome-atlas/atlas/blob/master/atlas/rules/cat_taxonomy.smk#L8 The left side of the join has a value (`genomes/genomes`) but the right side is empty I guess (`"{genome}.fasta".format(**wc)`), otherwise it should be used isn't it? And then you get a error complaining that the input is a directory and not a file.

**Comment by mdehollander** [comment] 2019-07-19 13:36
I downgraded atlas to version 2.0.5 and now it works, although snakemake off-course gives now warnings that the dynamic flag needs to be replaced with checkpoints.

If I change the `get_genome_for_cat` in the current master by removing the `get_genome_dir_(wc)` call it works, although then prodigal gets no input in the `predict_genes_of_genomes.py` script. So there is something not right yet with the checkpoints and the use of functions as input. So the code from March works for me: https://github.com/metagenome-atlas/atlas/blob/8799a9e06992beb7a2bd9515cd6dd40282492d45/atlas/rules/cat_taxonomy.smk#L8

Hope this helps a bit debugging. If you need additional output, please let me know.

**Comment by SilasK** [comment] 2019-07-19 19:40
How did you remove the call to get_genome_dir_ call? PR if this is easier.

**Comment by mdehollander** [comment] 2019-07-22 09:34
I have nothing to PR, since what 'works' is the code of version `2.0.5`. But this still uses the `dymanic` function and is not snakemake `5.6.0` ready.

I put works in quotes, because here I experience the bug in CAT (#199) again. A 11 TB file (`MAG4.concatenated.fasta`) was written to disk and it kept writing. I will try what happens after updating CAT to the latest release, because here 4.3.3 is still used and 4.6 is the latest version.

**Comment by SilasK** [comment] 2019-07-22 12:11
@mdehollander I'm not able to recreate your error. I know the checkpoints are weird. 

When I used atlas 2.1.3 with snakemake 5.5.4 conda 4.7.8+ . I would run, the predeict genes and CAT.  
 a big fix came with snakemake 5.4.3

**Comment by mdehollander** [comment] 2019-07-24 12:11
Strange, I tried in a new dir, with 2 samples, ran atlas init and than executed `atlas run genomes` and still get the same error:
```
Job counts:
        count   jobs
        1       get_genome_for_cat
        1
RuleException:
IsADirectoryError in line 14 of ***/atlas/atlas/rules/cat_taxonomy.smk:
[Errno 21] Is a directory: 'genomes/genomes'
  File "***/atlas/atlas/rules/cat_taxonomy.smk", line 14, in __rule_get_genome_for_cat
  File "***.conda/envs/atlas/lib/python3.6/shutil.py", line 241, in copy
  File "***.conda/envs/atlas/lib/python3.6/shutil.py", line 120, in copyfile
  File "***.conda/envs/atlas/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
```
I am using atlas 2.1.3 installed from git with pip, and snakemake 5.5.4 and conda 4.7.10. I thought it might be a python error, so I also tried with python 3.7.3, without success. What can it be? The list of packages in my conda environment is here: https://paste.ubuntu.com/p/WyRjJWKSRd/

This part is not tested with CI, isn't?

**Comment by SilasK** [comment] 2019-07-24 14:17
No,  I'm working on a way how to put the binning part on circle ci (
without having to do an assembly).

When you are using the newest master from github you can circumvent the
checkpoints :

1.  run 'atlas run genome'
untill the error, this creates the directory of MAGs 'genomes/genomes'
2.  Run again and add the following option to the comand line:

--config genome_dir="genomes/genomes"

**Comment by mdehollander** [comment] 2019-07-24 14:46
Hmm, I get this:
```
$ atlas run genomes --config genome_dir="genomes/genomes"
[2019-07-24 16:42 INFO] Executing: snakemake --snakefile ***/atlas/atlas/Snakefile --directory /*** --jobs 80 --rerun-incomplete --configfile '/***/config.yaml' --nolock  --use-conda  --conda-prefix /***/databases/conda_envs   genomes  --config genome_dir=genomes/genomes 
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/***/genomes/genomes
/***/genomes/genomes/MAG1.fasta
[2019-07-24 16:42 CRITICAL] Command 'snakemake --snakefile ***/atlas/atlas/Snakefile --directory /*** --jobs 80 --rerun-incomplete --configfile '/***/config.yaml' --nolock  --use-conda  --conda-prefix /***/databases/conda_envs   genomes  --config genome_dir=genomes/genomes ' returned non-zero exit status 1.
```

**Comment by SilasK** [comment] 2019-07-24 15:20
I’m on the way of finding the bug in a test example.

For now, if you rename the genome dir “genomes/genomes” to e.g. genomes/GENOMES” and adapt the config option, it should work.

**Comment by mdehollander** [comment] 2019-07-24 15:50
:+1: That is a good workaround for now. Thanks.

**Comment by SilasK** [comment] 2019-07-25 09:04
I raised an [issue](https://bitbucket.org/snakemake/snakemake/issues/1239/weird-behaviour-of-input-functions-after) on the snakemake repository. Stay tuned. 

Thank you for persevering in the debugging process!

**Comment by SilasK** [comment] 2019-09-20 12:48
Duplicate of #231

**Closed by SilasK** 2019-09-20 12:48 UTC
